### ISSUE TITLE
build is failing

### ISSUE THREAD

**Issue by 1vish99** [evolv34/graphite-kafka-connect#10]
Build is failing with the below error

```
[info] - should take the time from message and write the sink record to timeseries database *** FAILED ***
[info]   java.net.ConnectException: Connection refused
[info]   at java.net.PlainSocketImpl.socketConnect(Native Method)
[info]   at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[info]   at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[info]   at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[info]   at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[info]   at java.net.Socket.connect(Socket.java:589)
[info]   at java.net.Socket.connect(Socket.java:538)
[info]   at java.net.Socket.<init>(Socket.java:434)
[info]   at java.net.Socket.<init>(Socket.java:211)
[info]   at com.evolv.metrics.reporter.GraphiteReporter.<init>(GraphiteReporter.scala:11)
```

**Comment by evolv34** [comment]
Let me take a look at it

**Comment by evolv34** [comment]
@1tarak Can you try it now ? I have fixed it. Let me know if you are still seeing issue.
